### ISSUE TITLE
Any migration step from ActiveAndroid

### ISSUE THREAD

**Issue by NeoLSN** [ImangazalievM/ReActiveAndroid#1]
Just hope there is an document can describe that. Many thanks you re-active my app again.

**Comment by ImangazalievM** [comment]
Hello! Please see this page: [Migration from ActiveAndroid](https://imangazalievm.gitbooks.io/reactiveandroid/content/migration-from-activeandroid.html)

**Comment by duckinferno** [comment]
This link is dead.

**Comment by ImangazalievM** [comment]
@duckinferno fixed. Thanks

**Comment by duckinferno** [comment]
Thanks for creating this fork. :)
