### ISSUE TITLE
inner join query throwing an error if it returns empty

### ISSUE THREAD

**Issue by erhanbicer** [ImangazalievM/ReActiveAndroid#12]
hello again,
if the database contents are empty, it throwing the error below

![](https://i.hizliresim.com/XPpNd0.png)

but,
with try catch, the solution can be found, but would not it be better for the library itself to check it?

![](https://i.hizliresim.com/QVGNQv.png)

**Comment by ImangazalievM** [comment]
Fixed in `1.3.5`. Thanks for report!
