### ISSUE TITLE
TypeSerializer does not support byte[] ?

### ISSUE THREAD

**Issue by alzhuravlev** [ImangazalievM/ReActiveAndroid#13]
TypeSerializer.java
raise an exeption if I use byte[] as SerializedType
        this.serializedTypeClass = (Class<SerializedType>) parameterizedType.getActualTypeArguments()[1];

how to serialize into byte[] ?

**Comment by ImangazalievM** [comment]
Added blob support in version `1.4.0`. Please use class `Blob` as wrapper for byte array:

```java
public class CustomTypeSerializer extends TypeSerializer<MyCustomType, Blob> {

    @Nullable
    @Override
    public Blob serialize(@Nullable MyCustomType data) {
        return new Blob(data.toString().getBytes());
    }

    @Nullable
    @Override
    public MyCustomType deserialize(@Nullable Blob data) {
        return MyCustomType.getByName(new String(data.getBlob()));
    }

}
```

**Comment by alzhuravlev** [comment]
Great! thank you!

**Comment by alzhuravlev** [comment]
I managed to use String (instead Blob). But I will rewrite to use Blob
