### ISSUE TITLE
.exists() method

### ISSUE THREAD

**Issue by DanielStankovic** [ImangazalievM/ReActiveAndroid#14]
Is there .exists() method in ReActiveAndroid like there was in ActiveAndroid? Maybe under a different name? Thank you in advance

**Comment by ImangazalievM** [comment]
ReActiveAndroid hasn't `exists` method, so you must use the following method:

```java
Select.from(MyTable.java).count() > 0
```

**Comment by DanielStankovic** [comment]
Thank you so much.

**Comment by ImangazalievM** [comment]
You’re welcome)
