### ISSUE TITLE
E/SQLiteLog: (1) near "LIMIT": syntax error

### ISSUE THREAD

**Issue by Bennith** [ImangazalievM/ReActiveAndroid#15]
I am using fetchSingle() to check if any hits (via "id", 1) and get hit with E/SQLiteLog: (1) near "LIMIT": syntax error when processing (I know no rows in related queried table) but should return 0 or a false value but instead get Exception error ...

Any advice?

**Comment by ImangazalievM** [comment]
Can you provide your query code and stacktrace?

**Comment by Bennith** [comment]
was this fixed in the commit https://github.com/ImangazalievM/ReActiveAndroid/commit/50f088adb80c8887eb147bc8ecf90a140297fa16

**Comment by ImangazalievM** [comment]
Great!
