### ISSUE TITLE
What is the purpose of disableMigrationsChecking ()?

### ISSUE THREAD

**Issue by erhanbicer** [ImangazalievM/ReActiveAndroid#17]
even if you do not change the table structure, all columns are deleted when you upgrade the database version. why ?

**Comment by ImangazalievM** [comment]
It can be useful when you develop your application and the database scheme frequently change. You can remove `disableMigrationsChecking()` before releasing your app.

**Comment by erhanbicer** [comment]
I removed it before releasing and the application failed again and closed. Sorry, but this library is a complete waste of time and I don't want to waste more time with this library. I wish you good work.
