### ISSUE TITLE
Order List

### ISSUE THREAD

**Issue by jeremy-jamez** [ImangazalievM/ReActiveAndroid#2]
I am displaying notifications in a recyclerview and would like to order it by showing the newest notification on top. I've tried using `orderBy("timestamp")`, but it orders it from oldest to newest. `timestamp` is saved as a long which is basically me saving `System.currentmillis()` whenever a new notification is received. How can I reverse the current ordering?
`notificationses = Select.from(Notifications.class).orderBy("timestamp").fetch();`

**Comment by ImangazalievM** [comment]
Try this:

`Select.from(Notifications.class).orderBy("timestamp DESC").fetch();`
