### ISSUE TITLE
Use select without id query

### ISSUE THREAD

**Issue by Bennith** [ImangazalievM/ReActiveAndroid#20]
Aiming to get results from a query using just the below without passing an id, as the docs state .where() needs a id as first param ...

_"The second parameter is to pass the query arguments"_

    Note note = Select.from(TodayInfo.class).where("title = LIKE '?%'", query).fetchSingle();

I am also getting the below error even with straight up docs example ..

    E/SQLiteLog: (1) near "'?%'": syntax error

**Comment by ImangazalievM** [comment]
Your "where" clause is incorrect. Correct version:

```java
Note note = Select.from(TodayInfo.class).where("title LIKE '?%'", query).fetchSingle();
```

**Comment by Bennith** [comment]
Ok I see the syntax error, thanks.

Does that mean the docs have incorrect syntax as taken per below, with the "=" before "LIKE" query

Note note = Select.from(TodayInfo.class).where("id = ? AND title = LIKE '?%'", 1, query).fetchSingle();

**Comment by ImangazalievM** [comment]
Yes, you are right. I will fix it. Thanks!
