### ISSUE TITLE
Unable to update Mulitple Data at that time 1.4.2 

### ISSUE THREAD

**Issue by sathyaventhan** [ImangazalievM/ReActiveAndroid#21]
Thanks for using ReActiveAndroid but before you post an issue, please consider the following points:

  - [x] Please include the library version number, including the minor and patch version, in the issue text.

  - [ ] If you think you found a bug, please include a code sample that reproduces the problem. Dumping a stacktrace is usually not enough for us.

**Comment by ImangazalievM** [comment]
Can you provide more information about your problem, please?

**Comment by sathyaventhan** [comment]
Hi ,
  I want to update   two colums  data using one query its is possible.now
want i am doing  i am excuting two query updating two columbs

**Comment by ImangazalievM** [comment]
Can you provide code of your queries?

**Comment by ImangazalievM** [comment]
@sathyaventhan you can update two or more columns in this way:

```java
Update.table(Note.class).set("title = ?, text = ?", "New title", "New text").where("id = ?", 1).execute();
```

**Comment by sathyaventhan** [comment]
Thanks lot
