### ISSUE TITLE
open existing db

### ISSUE THREAD

**Issue by croccio** [ImangazalievM/ReActiveAndroid#23]
Thanks for using ReActiveAndroid but before you post an issue, please consider the following points:

  - [1.4.3]

I need to create a DB every day. How can I do it?
And how can I open DB created in past days? 

THanks

**Comment by minhnxx** [comment]
Seems like they dont support this lib anymore...

**Comment by ImangazalievM** [comment]
@minhnxx Hello. It's not true. The question is not clear, so I can't understand what he wants to do.
