### ISSUE TITLE
I am migrating from active android. How can I continue with old database version without losing data which are in user's mobile? 

### ISSUE THREAD

**Issue by yashpalraj** [ImangazalievM/ReActiveAndroid#25]

**Comment by ImangazalievM** [comment]
Just configure ReActiveAndroid and specify the same database filename (without extension) as you specified for ActiveAndroid. If you changed the database scheme, you must provide the migration.

I recommend checking the migration from the old version to the new one before you publish a new version of your application.

More information you can find [here](https://github.com/ImangazalievM/ReActiveAndroid).

**Comment by yashpalraj** [comment]
Thanks for quick reply. Migration done without losing data.
