### ISSUE TITLE
What is the key used to encrypt database?

### ISSUE THREAD

**Issue by hamza-am100** [ImangazalievM/ReActiveAndroid#26]
Im trying to view the database of my app, but the database is encrypted. Do you know where i can find the key or how the key is generated.

**Comment by ImangazalievM** [comment]
Hello! ReActiveAndroid does not use database encryption.

**Comment by hamza-am100** [comment]
Thats weird maybe the OS is encrypting it or something, Thank you for you help and fast response, im going to look further.

**Comment by ImangazalievM** [comment]
Android OS does not encrypt an app database. How do you open your database? Maybe the database file is damaged?
