### ISSUE TITLE
Usage with existing database

### ISSUE THREAD

**Issue by murat-mehmet** [ImangazalievM/ReActiveAndroid#27]
I have just migrated from ActiveAndroid due to errors on Android 8+

The problem is that my app comes with db-first approach. The database, which has all the tables and data, gets installed with app. In ActiveAndroid I used to have my db in assets folder and it would handle the else correctly. However after migration the fetch commands return empty. I think the db file in assets is not used and ReActiveAndroid just creates a new one.

The filename is in 'mydatabase.db' format and my appdatabase.js:
```
@Database(name = "mydatabase", version = 1)
public class AppDatabase {
}
```

So is there something that I'm missing?

**Comment by ImangazalievM** [comment]
ReActiveAndroid doesn't support work with a database from `assets` folder. To do it, you must copy your `db` file to `databases` folder manually before ReActiveAndroid have been initialized.

**Comment by murat-mehmet** [comment]
Got it thanks! Then this could be a feature-request. It could be useful to look for db in assets folder if it does not exist in database folder, then copy it and use it. For now I will do it manually, thanks for the great lib anyway!

**Comment by ImangazalievM** [comment]
Good luck :wink:
