### ISSUE TITLE
How to select distinct records

### ISSUE THREAD

**Issue by minhnxx** [ImangazalievM/ReActiveAndroid#28]
Hi dear,

How can I select distinct in ReActiveAndroid, I'm trying to select this way but it requires Object as parameter but not model class

Select.distinct().from(...)
I'm using version 1.4.3
Thanks

**Comment by ImangazalievM** [comment]
Hello! Can you give me SQL query string, please?

**Comment by cviacmob** [comment]
public static List getRyotMasterList() {
return Select.distinct().columns("mobile_1").from(RyotMasterDb.class).orderBy("remoteID DSC").fetch();
}
mobile_1---> this is the column name . kindly check my code
