### ISSUE TITLE
java.lang.IllegalStateException: Type serializer for type 'com.example.myenumclass' not found

### ISSUE THREAD

**Issue by ashwindmk** [ImangazalievM/ReActiveAndroid#29]
I am trying to migrate from activeandroid to reactiveandroid. I need to add an enum class as column within a model class, how to do that in reactive-android?

**Comment by ImangazalievM** [comment]
Hello. For custom types in models you must provide TypeSerializer to serialize field into one of the supported types. For more information see [this page](https://imangazalievm.gitbooks.io/reactiveandroid/type-converters.html).

**Comment by ashwindmk** [comment]
Thanks for the link. The problem was it used to work in active-android without any type converters, I guess it used to take string value of the enum, if no type converter is specified. But this started to crash after migration to reactive-android.

**Comment by ImangazalievM** [comment]
@ashwindmk Yes, ActiveAndroid automatically converts Enum to a string, but this is not correct, in my opinion. [Here](https://github.com/ImangazalievM/ReActiveAndroid/blob/0b59fef0160674906478f00d8b32e52053fdf8e8/reactiveandroid/src/test/java/com/reactiveandroid/internal/serializer/integrationtest/CustomTypeSerializer.java) you can find an example of TypeSerializer for enum, that converts it to Blob type (but you can replace it to String).
