### ISSUE TITLE
tip changed schema everytime i debug in as3.0

### ISSUE THREAD

**Issue by restmad** [ImangazalievM/ReActiveAndroid#3]
'Looks like you've changed schema but forgot to update the version number'

don't want to see this when i modify program, debug app in android studio, how can i fix this?

**Comment by restmad** [comment]
oops, i changed the model. sorry.

**Comment by ImangazalievM** [comment]
You can also disable migration checking, while you are debugging your app:

```java
DatabaseConfig appDatabaseConfig = new DatabaseConfig.Builder(AppDatabase.class)
                ...
                .disableMigrationsChecking()
                .build();
```

In this case, ReActiveAndroid will delete all tables and recreate and create them again.
