### ISSUE TITLE
How to retrieve Model IDs?

### ISSUE THREAD

**Issue by ikrits** [ImangazalievM/ReActiveAndroid#30]
Hi,
I'm currently migrating an app from ActiveAndroid to ReActiveAndroid. One of the issues I've run into is the lack of a getId() method from the Model class that was present in ActiveAndroid. Some of my Model classes rely on this method. Is there some other way to retrieve the Model ID inside a Model class?

Any help would be appreciated, thank you.

**Comment by peterdk** [comment]
If not specified earlier in ActiveAndroid models, you could add primary key fields that match the original autogenerated ones? 
```
@PrimaryKey(name="Id")
private Long Id;
```

**Comment by ImangazalievM** [comment]
Hello. Please read [this article](https://imangazalievm.gitbooks.io/reactiveandroid/migration-from-activeandroid.html).
