### ISSUE TITLE
Create a new new record to save multiple duplicate data in saved in the database using mobile network only, how to solve

### ISSUE THREAD

**Issue by cviacmob** [ImangazalievM/ReActiveAndroid#34]
Thanks for using ReActiveAndroid but before you post an issue, please consider the following points:

  - [ ] Please include the library version number, including the minor and patch version, in the issue text.

  - [ ] If you think you found a bug, please include a code sample that reproduces the problem. Dumping a stacktrace is usually not enough for us.

**Comment by ImangazalievM** [comment]
This does not seem like a ReActiveAndroid issue. I can't help you without more information.

**Comment by cviacmob** [comment]
I attached the reference Link: https://github.com/oogbox/odoo-mobile

OdooValues values = new OdooValues();
values.put("post_code", mPostalCode.getText());
client.create("ryot.master", values, new IOdooResponse() {
@override
public void onResult(OdooResult result) {
int serverId = result.getInt("result");
Toast.makeText(getActivity(), "Save Successfully", Toast.LENGTH_LONG).show();
getActivity().onBackPressed();

        }

    });
