### ISSUE TITLE
Create the new record for image upload refelct the duplicate data saved in the database 

### ISSUE THREAD

**Issue by cviacmob** [ImangazalievM/ReActiveAndroid#35]
Thanks for using ReActiveAndroid but before you post an issue, please consider the following points:

  - [ ] Please include the library version number, including the minor and patch version, in the issue text.

  - [ ] If you think you found a bug, please include a code sample that reproduces the problem. Dumping a stacktrace is usually not enough for us.

**Comment by ImangazalievM** [comment]
This does not seem like a ReActiveAndroid issue. I can't help you without more information.
