### ISSUE TITLE
Using Transaction for large Data ~15k entries

### ISSUE THREAD

**Issue by bhapps** [ImangazalievM/ReActiveAndroid#36]
Current Version: _com.reactiveandroid:reactiveandroid:1.4.3_

I have, on launch a scenario of comparing local string & server side string, and on false, I run an update to my DB which has data pulled from API (~15k items) in which I pass this data to public static helper to do DB updates on the tables;

Problem is when I use begin/end transaction in this method(), even though the save() passes true, nothing gets actually added or updated (get count of 0), but if I remove the begin/end transaction everything gets updated/created in the DB as i should (get count of ~15k) but is very slow and not ideal at all;

Also both types freeze the UI indefinitely until task completed;

**Comment by bhapps** [comment]
Moved code to pass through AsyncTask to stop UI freezing (worked), however, the below,

> _begin/end transaction, even though the `if(class.save() > 0){} `passes true on each data item (in List<>), nothing gets actually added or updated (get count of 0)_

still persists..

**Comment by ImangazalievM** [comment]
1. Can you create a test project, that reproduces your problem?
2. To avoid UI freezing you have to perform your operations with a database in the background thread.

**Comment by ImangazalievM** [comment]
@Bennith can you create a simple project that reproduces your problem, and share it on GitHub?

**Comment by bhapps** [comment]
@ImangazalievM 

Please see sample project which uses transaction to add data (which still fails), but turning off transactions data is added (getting counts of 15K rows)

Change `public static boolean useTransactions = true;`  in [MainApplication](https://github.com/Bennith/ORMTransactionExample/blob/master/app/src/main/java/ormtransaction/example/application/core/MainApplication.java) to enable/disable transaction

Please see [ORMHelpers ](https://github.com/Bennith/ORMTransactionExample/blob/a89b0610fe4bcb046121b246b843b01953d1f294/app/src/main/java/ormtransaction/example/application/orm/ORMDBHelpers.java#L19)file and the method `public static Boolean setRowData(List<String> getPassedData)` which processes the passed data;

[https://github.com/Bennith/ORMTransactionExample](https://github.com/Bennith/ORMTransactionExample)

**Comment by ImangazalievM** [comment]
I will check it out soon. Unfortunately, I have a lot of work to do now.

**Comment by bhapps** [comment]
Maybe it is due to missing the `setTransactionSuccessful() `to do the actual commit.
I will test this on my side to confirm.

_How you can use database transaction in Android_
- If you want to start the transaction there is a method `beginTransaction()`
- If you want to commit the transaction there is a method `setTransactionSuccessful() `which will commit the values in the database
-  If you had start the transaction you need to close the transaction so there is a method `endTransaction()` which will end your database transaction

If so, can we add this to the documentation [transactions](https://imangazalievm.gitbooks.io/reactiveandroid/transactions.html)

**Comment by bhapps** [comment]
Confirmed, It is due to the missing line code `setTransactionSuccessful()`
`beginTransaction()`
`/* do sql work here */`
`ReActiveAndroid.getDatabase(ORMAppDatabase.class).getWritableDatabase().setTransactionSuccessful();`
`endTransaction()`

**Comment by ImangazalievM** [comment]
@Bennith Good job! I will add new API for working with transactions in the new version.
