### ISSUE TITLE
How to hide single row  in table

### ISSUE THREAD

**Issue by cviacmob** [ImangazalievM/ReActiveAndroid#37]
Thanks for using ReActiveAndroid but before you post an issue, please consider the following points:

  - [ ] Please include the library version number, including the minor and patch version, in the issue text.

  - [ ] If you think you found a bug, please include a code sample that reproduces the problem. Dumping a stacktrace is usually not enough for us.

**Comment by ImangazalievM** [comment]
1. For changing a database scheme, you have to use [migrations](https://imangazalievm.gitbooks.io/reactiveandroid/migrations.html). Increment database version and provide migration for that version. If you previously had version 4 on a device, you need to change the version to 5. For more info visit this page: [Migrations](https://imangazalievm.gitbooks.io/reactiveandroid/migrations.html).

2. The instructions for adding/deleting a column in a table, you can find [here](https://stackoverflow.com/questions/8442147/how-to-delete-or-add-column-in-sqlite).
