### ISSUE TITLE
How to use Foreign Key Constraints

### ISSUE THREAD

**Issue by JuanCross23** [ImangazalievM/ReActiveAndroid#4]
I need to enable Cascade on Delete in my database. I was wondering if that would be the default behaviour but I guess it doesn't matter if I didn't specify a Foreign Key in my class. Also, the [Relationship](https://imangazalievm.gitbooks.io/reactiveandroid/content/relationships.html) part is missing in the documentation.

**Comment by ImangazalievM** [comment]
You can specify ON DELETE/UPDATE behavior using onDelete/onUpdate attributes in `Column` annotation:

```java
@Table(name = "Products", database = AppDatabase.class)
public class Product extends Model {

    ...
    @Column(name = "folder", onDelete = ForeignKeyAction.CASCADE)
    private Folder folder;

}
```
