### ISSUE TITLE
How to sort the list value?

### ISSUE THREAD

**Issue by cviacmob** [ImangazalievM/ReActiveAndroid#40]
ReActiveAndroid Version:

Bug or Feature Request:

Description:

**Comment by ImangazalievM** [comment]
There is an example of query with sorting by specified column:

```java
List<TestModel> list = Select
                .from(TestModel.class)
                .orderBy("intField ASC")
                .fetch();
```

**Comment by cviacmob** [comment]
this is working , thanks lot

**Comment by cviacmob** [comment]
how to use where condition using sorting
public static List<DocumentFourtyTable> getDo40ListPlot(String ryotID) {
        return Select.from(DocumentFourtyTable.class).where("plot_id LIKE '%" + ryotID + "%'").fetch();
    }

this is the my code how to use sort

**Comment by ImangazalievM** [comment]
```java
Select.from(DocumentFourtyTable.class)
    .where("plot_id LIKE '%" + ryotID + "%'")
    .orderBy("intField ASC")
    .fetch();
```

**Comment by cviacmob** [comment]
thanks you for your help
