### ISSUE TITLE
How to get distinct(remove duplicate) records 

### ISSUE THREAD

**Issue by cviacmob** [ImangazalievM/ReActiveAndroid#41]
ReActiveAndroid Version:

Bug or Feature Request:

Description:

**Comment by ImangazalievM** [comment]
There is an example of using the `distinct` clause:

```
Select.distinct().columns("a", "b", "c")
```

**Comment by cviacmob** [comment]
i need to Distinct the List<String> value

**Comment by ImangazalievM** [comment]
What you mean by "Distinct the List value"? The example above is a part of `SELECT` query with `DISTINCT` clause. There is the full example of the query:

```java
Select.distinct().columns("a", "b", "c").from(MyTable.class).fetch();
```

**Comment by cviacmob** [comment]
i import your code but its not working,
for example ,
 public static List<RyotMasterDb> getRyotMasterList() {
        return Select.distinct().columns("mobile_1").from(RyotMasterDb.class).orderBy("remoteID DESC").fetch();
    }
mobile_1---> this is the column name . kindly check my code
