### ISSUE TITLE
How to set database file location

### ISSUE THREAD

**Issue by rmunk** [ImangazalievM/ReActiveAndroid#44]
ReActiveAndroid Version: 1.4.3

I am migrating from ActiveAndroid where I used to build a database dynamically and set the database file location using `Configuration.Builder.setDatabaseName(name)` to the external files directory (e.g. /sdcard/Android/data/ch.photrack.discharge/files/discharge.db). That way database file can be directly accessed by user for debugging and exporting.

Is there a way to change the default location of database file in ReActiveAndroid? If not, how can I preserve data in already existing ActiveAndroid database file located in external files directory when user updates app to the version with ReActiveAndroid?

**Comment by ImangazalievM** [comment]
You can specify the path to a database directly in the `@Database` annotation, but without file extension `.db`, since ReActiveAndroid adds this extension automatically. For example:

```java
@Database(name = "/data/data/com.myapp/files/AppDatabase", version = 1)
```

**Comment by rmunk** [comment]
I was using `Context.getExternalFilesDir()` to set database path dynamically. Since path to the external storage can be inconsistent across different phones I cannot just hardcode this path in the annotation. Is there any way to set database path dynamically?
