### ISSUE TITLE
How to distinct select record 

### ISSUE THREAD

**Issue by cviacmob** [ImangazalievM/ReActiveAndroid#48]
ReActiveAndroid Version:
1.4.2
Bug or Feature Request:
this is below my code but can not distinct records solve my problem 
Description:
public static List getRyotMasterList() {
return Select.distinct().columns("mobile_1").from(RyotMasterDb.class).orderBy("remoteID DSC").fetch();
}
mobile_1---> this is the column name . kindly check my code

**Comment by ImangazalievM** [comment]
You have to specify the table class, not the database one
