### ISSUE TITLE
saveAsync not updated

### ISSUE THREAD

**Issue by restmad** [ImangazalievM/ReActiveAndroid#5]
how to use this feature, save model in background thread?
any document?

**Comment by ImangazalievM** [comment]
To start async operation you should specify a [Scheduler](http://reactivex.io/documentation/scheduler.html) and call `subscribe()` method:

```java
myNote.saveAsync()
    .subscribeOn(Schedulers.io())
    .subscribe();
```

For more information see this page: [Async operations](https://imangazalievm.gitbooks.io/reactiveandroid/content/async-operations.html)

**Comment by hasnain-ahmad** [comment]
How can i use both of `ActiveAndroid ` & `ReActiveAndroid ` ORM at same time?
Or the best way to migrate from  `ActiveAndroid ` to`ReActiveAndroid ` in production app's project?
