### ISSUE TITLE
How to switch between the `ActiveAndroid ` to `ReActiveAndroid ` ORM?

### ISSUE THREAD

**Issue by hasnain-ahmad** [ImangazalievM/ReActiveAndroid#69]
How to switch or migrate between the `ActiveAndroid ` to`ReActiveAndroid ` ORM in the production app's project?
Or can we use the both the ORMs in the same project? 
I want to save/insert my thousand of records to SQLite's tables asynchronously after getting the response from the Server in the form of JSON list of objects.

**Comment by hasnain-ahmad** [comment]
@ImangazalievM @dookah kindly suggest the solution to the problem.

**Comment by ImangazalievM** [comment]
@hasnain-ahmad Here you can find small guide: [Migration from ActiveAndroid.](https://imangazalievm.gitbooks.io/reactiveandroid/migration-from-activeandroid.html)
