### ISSUE TITLE
How to change datatype in Sqlitedatabase(Reactive android)

### ISSUE THREAD

**Issue by cviacmob** [ImangazalievM/ReActiveAndroid#70]
I change the data type convert to STRING to INT this is my below code Error. 

 public static final Migration MIGRATION_7_8=new Migration(7,8) {
        @Override
        public void migrate(SQLiteDatabase database) {
            database.execSQL("ALTER TABLE SeasonMasterDB ADD COLUMN dataValue INTEGER DEFAULT 0");
        }
    };

**Comment by yokikathir** [comment]
i have also same doubt ?

**Comment by ImangazalievM** [comment]
https://stackoverflow.com/questions/21199398/sqlite-alter-a-tables-column-type
