### ISSUE TITLE
JCenter is at end of life

### ISSUE THREAD

**Issue by persiscms** [ImangazalievM/ReActiveAndroid#74]
ReActiveAndroid Version: 1.4.3

Bug or Feature Request: Change hosting repository of ReActiveAndroid

Description:
Android Studio Arctic Fox Canary 8 started to warn that JCenter is at end of life. suggestion for jCenter replacement is MavenCentral but ReActiveAndroid is not hosted there.

**Comment by ImangazalievM** [comment]
Hey! Thanks for the warning. I will upload the library to Maven Central in 2-3 days
