### ISSUE TITLE
This line is incorrect in version 1.3.2 AggregateQueryBase.java#L149

### ISSUE THREAD

**Issue by erhanbicer** [ImangazalievM/ReActiveAndroid#9]
Will you fix this line? 

`System.out.println("sql: " + sql);`
  `System.out.println("getAsFloat: " + result);`

https://github.com/ImangazalievM/ReActiveAndroid/blob/c7f880117bc6a76f245ac5188507cc3f5b17cf48/reactiveandroid/src/main/java/com/reactiveandroid/query/AggregateQueryBase.java#L149

**Comment by ImangazalievM** [comment]
Fixed in version 1.3.3. Thanks!
